runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: woeclipse/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
DB_PASSWORD = ${{ secrets.SECRET_KEY}}