import os 


SECRET_KEY = '123456'
DATABASE_PASSWORD = os.getenv('DB_PASSWORD')
SQLALCHEMY_TRACK_MODIFICATIONS = False
DB_URL = 'postgresql+psycopg2://postgres:{pw}@35.198.159.181/woeclipse'.format(pw=DATABASE_PASSWORD)
SQLALCHEMY_DATABASE_URI = DB_URL